---
title: "Tableaux de bord des universités  \nv0.3"
author: "Julien Gossa  \n gossa@unistra.fr"
date: "09/01/2020"
output: 
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
    includes:
      in_header: header.tex
---

```{r setup, include=FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
knitr::opts_chunk$set(fig.width = 6, fig.height = 4, fig.align = "center", out.height="30%")

knitr::opts_chunk$set(pdf.options(encoding = "CP1250"))

library(kableExtra)
library(tidyverse)
library(cowplot)

library(pkiESR)

small_style <- list(
  point_size = 12,
  line_size = 2,
  text_size = 3,
  primaire_plot.margin = ggplot2::unit(c(0.25,0,0,0), "cm"),
  bp_width = 1,
  bp_text_x = -0.25 )

big_style <- list(
  point_size = 17,
  line_size = 2,
  text_size = 5,
  primaire_plot.margin = ggplot2::unit(c(0.3,0,0,0), "cm"),
  bp_width = 0.9,
  bp_text_x = -0.25 )


rentrée <- 2017
type <- "Université"

strvar <- function(var) {
  s <- as.character(var)
  ifelse(str_length(s)>0,s,"N/A")
}

catinfo <- function(etab) {
  cat("- ",strvar(etab$Type.détaillé))
  r <- strvar(etab$Rattachement)
  if(r == "N/A") cat(" sans rattachement ") else cat(" rattaché(e) à ",r)
  cat(" dans l'académie de ", strvar(etab$Académie), "\n")
  cat("- UAI : ",strvar(etab$UAI))
  cat(" ; Web : ",strvar(etab$url.siteweb) )
  cat(" ; [Wikidata](", strvar(etab$url.wikidata),")\n")
  cat(" ; [Décret](",strvar(etab$url.legifrance),")\n   \n")
}

table_classement <- function(rentrée,type,pkis,labels)
  pkiesr_classement(rentrée, type, pkis, labels) %>%
    kable("latex", longtable = T, booktabs = T, align = c("r","r","l",rep("r",4))) %>%
    kable_styling(latex_options = c("striped", "repeat_header"))
```

__ATTENTION : Ceci est un document de travail. Aucune donnée n'a été vérifiée.__

# Présentation des indicateurs


```{r child = 'tdbesr-manuel.Rmd', echo = FALSE, warning = FALSE}
```

\newpage
# Classements

## Taux de ressources propres

```{r classement.RP}
table_classement(rentrée, "Université",
                  c("pki.K.proPres", "pki.FIN.P.ressources","pki.FIN.S.ressourcesPropres"),
                  c("Taux","Ressources","Ressources   \nPropres"))
```

## Taux de ressources par étudiant (inscrit en cycles 1 (L) et 2 (M))

```{r classement.RpE}
table_classement(rentrée, "Université",
                  c("pki.K.resPetu", "pki.FIN.P.ressources","pki.ETU.S.cycle.1.L","pki.ETU.S.cycle.2.M"),
                  c("Taux","Ressources","Effectif L","Effectif M"))
```

## Taux de formations sélectives

```{r classement.FS}
table_classement(rentrée, "Université",
                  c("pki.K.selPfor", "pki.ADM.P.formations","pki.ADM.S.sélective"),
                  c("Taux","Formations","Formations sélectives"))
```

## Taux d'encadrement

```{r classement.EpE}
table_classement(rentrée, "Université",
                  c("pki.K.titPetu", "pki.ENS.S.titulaires","pki.ETU.P.effectif"),
                  c("Taux","Ens. titulaires","Etudiants"))
```

## Taux de titularité

```{r classement.TpE}
table_classement(rentrée, "Université",
                  c("pki.K.titPens", "pki.ENS.P.effectif", "pki.ENS.S.titulaires"),
                  c("Taux","Enseignants","Titulaires"))
```


```{r etab.loop, results="asis", message=FALSE, error=FALSE, fig.width=9,fig.height=10.5, out.height="100%"}
uai.unistra <- "0673021V"
uai.uha <- "0681166Y"
uai.ubm <- "0331766R"
uai.nimes <- "0301687W"
uai.lorraine <- "0542493S"
uai.guyanne <- "9730429D"
uai.bordeaux <- "0333298F"

uai.ehess <- "0753742K"
uai.dauphine <- "0750736T"


etabs <- subset(esr,Type %in% c("Université", "Grand établissement"), c(UAI,Libellé:url.legifrance) ) %>% unique %>% arrange(desc(Type),Académie)
#etabs <- filter(etabs, UAI %in% c(uai.unistra,uai.uha))

aca <- ""
type <- ""
for (i in seq(1,nrow(etabs))) {
  etab <- etabs[i,]
  message("Processing ",strvar(etab$Libellé))
  
  if(etab$Type != type) {
    cat("# Type d'établissement : ", strvar(etab$Type),"   \n")
    type <- etab$Type
  }
  cat("\\newpage   \n")  
  if(etab$Académie != aca) {
    cat("## Académie : ", strvar(etab$Académie),"   \n")
    aca <- etab$Académie
  }

  cat("### ", strvar(etab$Libellé),"(",strvar(etab$Sigle),")\n")
  
  catinfo(etab)
  
  print(pkiesr_plot_tdb(rentrée, etab$UAI, style.pki.k=big_style, style.pki=small_style))
  cat("  \n   \n")
}
```




